/**
 * WhatChangesPdfTemplate — Off-screen A4 PDF template
 * Captured by html2canvas → jsPDF
 * Width: 794px (A4 at 96dpi)
 */
import {
  NOMENCLATURE_CHANGES,
  OPERATIONAL_CHANGES,
  RATE_CHANGES,
  WHAT_STAYS_SAME,
  getBusinessHighlights,
} from "../../data/newTaxAct";

const KA_NAVY  = "#1a3a6b";
const KA_GREEN = "#8ab45a";

const DISCLAIMER =
  "This report is generated by the Kolte & Associates LLP Compliance Dashboard — a system-generated knowledge tool. " +
  "All facts, figures, and provisions stated herein are based on the Income Tax Bill, 2025 as introduced in Parliament on " +
  "13 February 2025, and are subject to amendments, notifications, and final enactment. " +
  "This document is intended solely for knowledge and information purposes. " +
  "The information should be cross-checked with the relevant statutory provisions and your professional consultant before any " +
  "reliance or action is taken. Action taken on the basis of this information shall be the sole responsibility of the user. " +
  "Kolte & Associates LLP, its partners, and associates shall not be liable for any loss, damage, or consequence arising " +
  "from use of this report.";

const CONTACT = {
  emails: ["ca.rohit@Kolte.biz", "ca.pawan@kolte.biz"],
  phones: ["+91 9764488999", "+91 9049222233"],
};

// ── Small branded page header (used on every section after cover) ─────────────
function PageHeader({ clientName }) {
  return (
    <div style={{
      display: "flex", alignItems: "center", justifyContent: "space-between",
      borderBottom: `3px solid ${KA_NAVY}`, paddingBottom: 10, marginBottom: 20,
    }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
        <div style={{ display: "flex", gap: 2 }}>
          {["K", "&", "A"].map((ch, i) => (
            <div key={i} style={{
              width: 24, height: 26, background: KA_GREEN,
              display: "flex", alignItems: "center", justifyContent: "center",
              borderRadius: 3,
            }}>
              <span style={{ color: KA_NAVY, fontWeight: 900, fontSize: 11, fontFamily: "Georgia, serif" }}>{ch}</span>
            </div>
          ))}
        </div>
        <div>
          <div style={{ fontSize: 9, fontWeight: 700, color: KA_NAVY }}>Kolte &amp; Associates LLP, Chartered Accountants</div>
          <div style={{ fontSize: 8, color: "#6b7280" }}>New Income Tax Act 2025 — Impact Report</div>
        </div>
      </div>
      <div style={{ fontSize: 8, color: "#6b7280", textAlign: "right" }}>
        <div style={{ fontWeight: 600 }}>{clientName}</div>
        <div>{new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}</div>
      </div>
    </div>
  );
}

// ── Small page footer ─────────────────────────────────────────────────────────
function PageFooter({ page, total }) {
  return (
    <div style={{
      marginTop: 24, paddingTop: 10,
      borderTop: `1px solid #e5e7eb`,
      display: "flex", justifyContent: "space-between", alignItems: "center",
    }}>
      <div style={{ fontSize: 7, color: "#9ca3af", maxWidth: 440, lineHeight: 1.4 }}>
        System-generated compliance report. For knowledge purposes only. Cross-check with your consultant before acting.
        Responsibility for use rests with the user.
      </div>
      <div style={{ fontSize: 8, color: "#9ca3af" }}>Page {page} of {total}</div>
    </div>
  );
}

// ── Section heading ───────────────────────────────────────────────────────────
function SectionTitle({ icon, title, subtitle }) {
  return (
    <div style={{
      background: `linear-gradient(135deg, ${KA_NAVY}, #2a5298)`,
      borderRadius: 8, padding: "12px 16px", marginBottom: 16, color: "white",
    }}>
      <div style={{ fontSize: 14, fontWeight: 800 }}>{icon} {title}</div>
      {subtitle && <div style={{ fontSize: 9, color: "#bfdbfe", marginTop: 3 }}>{subtitle}</div>}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
export default function WhatChangesPdfTemplate({ clientInfo }) {
  const natureValue = clientInfo?.nature?.value || "default";
  const highlights  = getBusinessHighlights(natureValue);
  const name        = clientInfo?.name || "Taxpayer";
  const nature      = clientInfo?.nature?.label || "Business";
  const today       = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" });
  const refNo       = `KA/WCM/${Date.now().toString(36).toUpperCase().slice(-6)}`;

  const highOps = [
    ...OPERATIONAL_CHANGES.all.filter((o) => o.impact === "High"),
    ...OPERATIONAL_CHANGES.all.filter((o) => o.impact === "Medium"),
    ...(OPERATIONAL_CHANGES.business || []),
    ...(OPERATIONAL_CHANGES.professional || []),
  ];

  return (
    <div id="wcm-pdf-template" style={{
      width: 794, fontFamily: "'Segoe UI', Arial, sans-serif",
      color: "#1f2937", background: "white", lineHeight: 1.5,
    }}>

      {/* ══════════════════════════════════════════════════ PAGE 1 — COVER */}
      <div style={{ padding: "0 0 32px 0", minHeight: 1122 }}>

        {/* Top brand bar */}
        <div style={{
          background: `linear-gradient(135deg, ${KA_NAVY} 0%, #2a5298 100%)`,
          padding: "28px 40px", color: "white",
          display: "flex", justifyContent: "space-between", alignItems: "flex-start",
        }}>
          {/* Logo + name */}
          <div>
            <div style={{ display: "flex", gap: 4, marginBottom: 10 }}>
              {["K", "&", "A"].map((ch, i) => (
                <div key={i} style={{
                  width: 40, height: 44, background: KA_GREEN,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  borderRadius: 5, boxShadow: "0 2px 6px rgba(0,0,0,0.3)",
                }}>
                  <span style={{ color: KA_NAVY, fontWeight: 900, fontSize: 18, fontFamily: "Georgia, serif" }}>{ch}</span>
                </div>
              ))}
            </div>
            <div style={{ fontSize: 16, fontWeight: 800, letterSpacing: 0.5 }}>Kolte &amp; Associates LLP</div>
            <div style={{ fontSize: 11, color: KA_GREEN, fontWeight: 600, letterSpacing: 1.5, textTransform: "uppercase", marginTop: 2 }}>
              Chartered Accountants
            </div>
            <div style={{ fontSize: 9, color: "#93c5fd", marginTop: 6 }}>
              ca.rohit@Kolte.biz &nbsp;|&nbsp; ca.pawan@kolte.biz
            </div>
            <div style={{ fontSize: 9, color: "#93c5fd" }}>
              +91 9764488999 &nbsp;|&nbsp; +91 9049222233
            </div>
          </div>

          {/* Report meta */}
          <div style={{ textAlign: "right" }}>
            <div style={{
              display: "inline-block", background: KA_GREEN, color: KA_NAVY,
              fontSize: 9, fontWeight: 800, padding: "4px 12px", borderRadius: 20,
              letterSpacing: 1.5, textTransform: "uppercase", marginBottom: 10,
            }}>
              Special Report
            </div>
            <div style={{ fontSize: 9, color: "#bfdbfe" }}>Report Ref: {refNo}</div>
            <div style={{ fontSize: 9, color: "#bfdbfe" }}>Date: {today}</div>
            <div style={{ fontSize: 9, color: "#bfdbfe", marginTop: 4 }}>Income Tax Bill, 2025</div>
            <div style={{ fontSize: 9, color: "#bfdbfe" }}>Introduced: 13 February 2025</div>
          </div>
        </div>

        {/* Report title block */}
        <div style={{ padding: "32px 40px 24px", textAlign: "center", borderBottom: `4px solid ${KA_GREEN}` }}>
          <div style={{ fontSize: 11, color: KA_GREEN, fontWeight: 700, letterSpacing: 3, textTransform: "uppercase", marginBottom: 8 }}>
            Personalised Impact Report
          </div>
          <div style={{ fontSize: 28, fontWeight: 900, color: KA_NAVY, lineHeight: 1.2, marginBottom: 6 }}>
            New Income Tax Act 2025
          </div>
          <div style={{ fontSize: 20, fontWeight: 700, color: "#374151", marginBottom: 4 }}>
            What Changes For Me?
          </div>
          <div style={{ fontSize: 11, color: "#6b7280", marginTop: 8 }}>
            Effective from <strong style={{ color: KA_NAVY }}>Tax Year 2026-27</strong> &nbsp;·&nbsp; Replaces Income Tax Act, 1961
          </div>
        </div>

        {/* Client details band */}
        <div style={{
          margin: "24px 40px", background: "#f0f4ff",
          border: `1px solid #c7d2f8`, borderRadius: 10, padding: "16px 24px",
          display: "flex", gap: 40,
        }}>
          <div>
            <div style={{ fontSize: 9, color: "#6b7280", fontWeight: 700, textTransform: "uppercase", letterSpacing: 1 }}>Prepared For</div>
            <div style={{ fontSize: 16, fontWeight: 800, color: KA_NAVY, marginTop: 3 }}>{name}</div>
          </div>
          <div>
            <div style={{ fontSize: 9, color: "#6b7280", fontWeight: 700, textTransform: "uppercase", letterSpacing: 1 }}>Business / Profession</div>
            <div style={{ fontSize: 14, fontWeight: 700, color: "#374151", marginTop: 3 }}>{nature}</div>
          </div>
          <div style={{ marginLeft: "auto" }}>
            <div style={{ fontSize: 9, color: "#6b7280", fontWeight: 700, textTransform: "uppercase", letterSpacing: 1 }}>Generated On</div>
            <div style={{ fontSize: 11, fontWeight: 600, color: "#374151", marginTop: 3 }}>{today}</div>
          </div>
        </div>

        {/* Top priorities */}
        {highlights.topChanges.length > 0 && (
          <div style={{ margin: "0 40px", background: `linear-gradient(135deg, ${KA_NAVY}15, ${KA_GREEN}10)`, border: `1px solid ${KA_NAVY}30`, borderRadius: 10, padding: "16px 20px" }}>
            <div style={{ fontSize: 10, fontWeight: 800, color: KA_GREEN, textTransform: "uppercase", letterSpacing: 1.5, marginBottom: 10 }}>
              🎯 Top Priorities for {nature}
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px 20px" }}>
              {highlights.topChanges.map((item, i) => (
                <div key={i} style={{ display: "flex", gap: 8, fontSize: 10, color: "#1f2937" }}>
                  <span style={{ color: KA_GREEN, fontWeight: 800, flexShrink: 0 }}>→</span>
                  <span>{item}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Report overview */}
        <div style={{ margin: "24px 40px 0" }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: KA_NAVY, textTransform: "uppercase", letterSpacing: 1, marginBottom: 12 }}>
            Report Contents
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr", gap: 10 }}>
            {[
              { num: "01", title: "Change in\nNomenclature", icon: "📝", desc: `${NOMENCLATURE_CHANGES.length} terms renamed` },
              { num: "02", title: "Changes in\nOperations", icon: "⚙️", desc: "New procedures" },
              { num: "03", title: "Change in\nRates",      icon: "📊", desc: "Updated tax slabs" },
              { num: "04", title: "What Does Not\nChange",  icon: "✅", desc: "Stable obligations" },
            ].map((item) => (
              <div key={item.num} style={{ background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 8, padding: "12px 12px 10px", textAlign: "center" }}>
                <div style={{ fontSize: 16, marginBottom: 4 }}>{item.icon}</div>
                <div style={{ fontSize: 8, fontWeight: 800, color: KA_NAVY, whiteSpace: "pre-line", lineHeight: 1.3 }}>{item.title}</div>
                <div style={{ fontSize: 8, color: "#6b7280", marginTop: 4 }}>{item.desc}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Cover footer */}
        <div style={{ margin: "32px 40px 0", paddingTop: 16, borderTop: "1px solid #e5e7eb" }}>
          <div style={{ fontSize: 7.5, color: "#9ca3af", lineHeight: 1.6 }}>
            <strong style={{ color: "#6b7280" }}>DISCLAIMER:</strong> {DISCLAIMER}
          </div>
        </div>
      </div>

      {/* ══════════════════════════════════════════════════ PAGE 2 — NOMENCLATURE */}
      <div style={{ padding: "32px 40px", minHeight: 1122, pageBreakBefore: "always" }}>
        <PageHeader clientName={name} />
        <SectionTitle icon="📝" title="Change in Nomenclature" subtitle="How the new Act renames key legal terms — effective from Tax Year 2026-27" />

        <div style={{ background: "#fffbeb", border: "1px solid #fcd34d", borderRadius: 8, padding: "10px 14px", marginBottom: 16, fontSize: 9.5, color: "#92400e" }}>
          <strong>What this means for you:</strong> All income tax forms, notices, and correspondence from the IT Department will use new terminology.
          Legal references in contracts and deeds should be updated accordingly over time.
        </div>

        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 9.5 }}>
          <thead>
            <tr style={{ background: KA_NAVY }}>
              <th style={{ padding: "10px 12px", textAlign: "left", color: "white", fontWeight: 700, width: "35%", borderRadius: "4px 0 0 0" }}>Old Term (IT Act 1961)</th>
              <th style={{ padding: "10px 12px", textAlign: "left", color: "white", fontWeight: 700, width: "30%" }}>New Term (IT Act 2025)</th>
              <th style={{ padding: "10px 12px", textAlign: "left", color: "white", fontWeight: 700, borderRadius: "0 4px 0 0" }}>What It Means</th>
            </tr>
          </thead>
          <tbody>
            {NOMENCLATURE_CHANGES.map((item, i) => (
              <tr key={i} style={{ background: i % 2 === 0 ? "white" : "#f9fafb" }}>
                <td style={{ padding: "8px 12px", color: "#dc2626", textDecoration: "line-through", fontWeight: 600, borderBottom: "1px solid #f3f4f6" }}>{item.old}</td>
                <td style={{ padding: "8px 12px", color: "#166534", fontWeight: 700, borderBottom: "1px solid #f3f4f6" }}>{item.newTerm}</td>
                <td style={{ padding: "8px 12px", color: "#4b5563", fontSize: 9, lineHeight: 1.5, borderBottom: "1px solid #f3f4f6" }}>{item.note}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <PageFooter page={2} total={5} />
      </div>

      {/* ══════════════════════════════════════════════════ PAGE 3 — OPERATIONS */}
      <div style={{ padding: "32px 40px", minHeight: 1122, pageBreakBefore: "always" }}>
        <PageHeader clientName={name} />
        <SectionTitle icon="⚙️" title="Changes in Operations" subtitle="New procedures, digital mandates, and compliance workflows under IT Act 2025" />

        <div style={{ marginBottom: 16 }}>
          <div style={{ fontSize: 10, fontWeight: 800, color: KA_NAVY, textTransform: "uppercase", letterSpacing: 1, marginBottom: 10, paddingBottom: 4, borderBottom: `2px solid ${KA_GREEN}` }}>
            Applies to All Taxpayers
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {OPERATIONAL_CHANGES.all.map((item, i) => (
              <div key={i} style={{ display: "flex", gap: 12, padding: "10px 12px", background: "#f8fafc", border: "1px solid #e5e7eb", borderRadius: 8 }}>
                <div style={{
                  flexShrink: 0, padding: "3px 8px", borderRadius: 20, fontSize: 8, fontWeight: 800, marginTop: 2,
                  background: item.impact === "High" ? "#fee2e2" : item.impact === "Medium" ? "#fef3c7" : "#dcfce7",
                  color: item.impact === "High" ? "#dc2626" : item.impact === "Medium" ? "#d97706" : "#16a34a",
                  border: `1px solid ${item.impact === "High" ? "#fca5a5" : item.impact === "Medium" ? "#fcd34d" : "#86efac"}`,
                }}>
                  {item.impact}
                </div>
                <div>
                  <div style={{ fontSize: 10, fontWeight: 700, color: "#1f2937", marginBottom: 3 }}>{item.title}</div>
                  <div style={{ fontSize: 9, color: "#4b5563", lineHeight: 1.5 }}>{item.description}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div>
          <div style={{ fontSize: 10, fontWeight: 800, color: "#16a34a", textTransform: "uppercase", letterSpacing: 1, marginBottom: 10, paddingBottom: 4, borderBottom: `2px solid ${KA_GREEN}` }}>
            Business &amp; Professional Specific
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {[...(OPERATIONAL_CHANGES.business || []), ...(OPERATIONAL_CHANGES.professional || [])].map((item, i) => (
              <div key={i} style={{ display: "flex", gap: 12, padding: "10px 12px", background: "#f0fdf4", border: "1px solid #bbf7d0", borderRadius: 8 }}>
                <div style={{
                  flexShrink: 0, padding: "3px 8px", borderRadius: 20, fontSize: 8, fontWeight: 800, marginTop: 2,
                  background: item.impact === "High" ? "#fee2e2" : "#fef3c7",
                  color: item.impact === "High" ? "#dc2626" : "#d97706",
                  border: `1px solid ${item.impact === "High" ? "#fca5a5" : "#fcd34d"}`,
                }}>
                  {item.impact}
                </div>
                <div>
                  <div style={{ fontSize: 10, fontWeight: 700, color: "#1f2937", marginBottom: 3 }}>{item.title}</div>
                  <div style={{ fontSize: 9, color: "#4b5563", lineHeight: 1.5 }}>{item.description}</div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <PageFooter page={3} total={5} />
      </div>

      {/* ══════════════════════════════════════════════════ PAGE 4 — RATES */}
      <div style={{ padding: "32px 40px", minHeight: 1122, pageBreakBefore: "always" }}>
        <PageHeader clientName={name} />
        <SectionTitle icon="📊" title="Change in Rates" subtitle="Updated tax slabs, capital gains rates, and deduction limits" />

        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          {RATE_CHANGES.map((cat, ci) => (
            <div key={ci} style={{ border: `1px solid ${cat.changed ? "#fcd34d" : "#e5e7eb"}`, borderRadius: 8, overflow: "hidden" }}>
              <div style={{ background: cat.changed ? "#fffbeb" : "#f8fafc", padding: "10px 14px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <div style={{ fontSize: 10, fontWeight: 700, color: "#1f2937" }}>{cat.category}</div>
                {cat.changed && (
                  <div style={{ background: "#fef08a", color: "#854d0e", fontSize: 8, fontWeight: 800, padding: "2px 10px", borderRadius: 20, border: "1px solid #fcd34d" }}>
                    CHANGED ⚠
                  </div>
                )}
              </div>
              <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 9.5 }}>
                <thead>
                  <tr style={{ background: KA_NAVY }}>
                    <th style={{ padding: "8px 12px", textAlign: "left", color: "white", fontWeight: 700 }}>Income Range / Category</th>
                    <th style={{ padding: "8px 12px", textAlign: "left", color: "white", fontWeight: 700, width: "30%" }}>Tax Rate</th>
                  </tr>
                </thead>
                <tbody>
                  {cat.slabs.map((s, si) => (
                    <tr key={si} style={{ background: si % 2 === 0 ? "white" : "#f9fafb" }}>
                      <td style={{ padding: "7px 12px", borderBottom: "1px solid #f3f4f6" }}>{s.income}</td>
                      <td style={{ padding: "7px 12px", fontWeight: 700, color: s.rate.includes("was") ? "#d97706" : "#166534", borderBottom: "1px solid #f3f4f6" }}>{s.rate}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
              {cat.note && (
                <div style={{ padding: "8px 12px", background: "#eff6ff", borderTop: "1px solid #bfdbfe", fontSize: 8.5, color: "#1d4ed8" }}>
                  ℹ {cat.note}
                </div>
              )}
            </div>
          ))}
        </div>

        <PageFooter page={4} total={5} />
      </div>

      {/* ══════════════════════════════════════════════════ PAGE 5 — UNCHANGED + DISCLAIMER */}
      <div style={{ padding: "32px 40px", minHeight: 1122, pageBreakBefore: "always" }}>
        <PageHeader clientName={name} />
        <SectionTitle icon="✅" title="What Does Not Change" subtitle="Core compliance obligations that remain identical under the new Act" />

        <div style={{ background: "#f0fdf4", border: "1px solid #bbf7d0", borderRadius: 8, padding: "10px 14px", marginBottom: 16, fontSize: 9.5, color: "#166534" }}>
          <strong>Good news:</strong> Despite significant structural changes, your core filing and payment obligations remain unchanged.
          Existing compliance calendars and workflows need minimal revision.
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginBottom: 32 }}>
          {WHAT_STAYS_SAME.map((item, i) => (
            <div key={i} style={{ background: "#f0fdf4", border: "1px solid #bbf7d0", borderRadius: 8, padding: "10px 12px", display: "flex", gap: 8 }}>
              <span style={{ color: "#16a34a", fontSize: 13, flexShrink: 0, marginTop: 1 }}>✓</span>
              <div>
                <div style={{ fontSize: 10, fontWeight: 700, color: "#1f2937", marginBottom: 2 }}>{item.point}</div>
                <div style={{ fontSize: 8.5, color: "#4b5563", lineHeight: 1.4 }}>{item.detail}</div>
              </div>
            </div>
          ))}
        </div>

        {/* Expert guidance CTA */}
        <div style={{
          background: `linear-gradient(135deg, ${KA_NAVY}, #2a5298)`,
          borderRadius: 10, padding: "20px 24px", color: "white", marginBottom: 24,
        }}>
          <div style={{ fontSize: 12, fontWeight: 800, marginBottom: 6 }}>Need Expert Guidance?</div>
          <div style={{ fontSize: 9.5, color: "#bfdbfe", marginBottom: 14, lineHeight: 1.5 }}>
            This report provides a structured summary of the key changes. For personalised advisory, tax planning,
            and compliance implementation specific to your business, connect with our team.
          </div>
          <div style={{ display: "flex", gap: 32 }}>
            <div>
              <div style={{ fontSize: 8, color: KA_GREEN, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1, marginBottom: 5 }}>Email Us</div>
              {CONTACT.emails.map((e, i) => (
                <div key={i} style={{ fontSize: 10, color: "white", fontWeight: 600 }}>📧 {e}</div>
              ))}
            </div>
            <div>
              <div style={{ fontSize: 8, color: KA_GREEN, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1, marginBottom: 5 }}>Call / WhatsApp</div>
              {CONTACT.phones.map((p, i) => (
                <div key={i} style={{ fontSize: 10, color: "white", fontWeight: 600 }}>📱 {p}</div>
              ))}
            </div>
            <div style={{ marginLeft: "auto", display: "flex", alignItems: "center" }}>
              <div style={{ textAlign: "center" }}>
                <div style={{ fontSize: 9, color: "#93c5fd" }}>🌐 Full interactive report</div>
                <div style={{ fontSize: 8, color: "#bfdbfe" }}>carohitai.github.io/compliancepro</div>
              </div>
            </div>
          </div>
        </div>

        {/* Full disclaimer box */}
        <div style={{ background: "#fafafa", border: "1px solid #e5e7eb", borderRadius: 8, padding: "16px 18px" }}>
          <div style={{ fontSize: 10, fontWeight: 800, color: "#374151", marginBottom: 8, display: "flex", alignItems: "center", gap: 6 }}>
            ⚠️ Disclaimer &amp; Important Notice
          </div>
          <div style={{ fontSize: 8.5, color: "#4b5563", lineHeight: 1.7 }}>
            {DISCLAIMER}
          </div>
          <div style={{ marginTop: 10, paddingTop: 8, borderTop: "1px dashed #d1d5db", fontSize: 8, color: "#6b7280", lineHeight: 1.5 }}>
            <strong>Sources:</strong> Income Tax Bill, 2025 (Lok Sabha) · incometaxindia.gov.in · PRS Legislative Research · ICAI publications ·
            Finance Act 2024 &nbsp;|&nbsp; <strong>Firm:</strong> Kolte &amp; Associates LLP, Chartered Accountants &nbsp;|&nbsp; <strong>Report Ref:</strong> {refNo}
          </div>
        </div>

        <PageFooter page={5} total={5} />
      </div>

    </div>
  );
}
